change_list=[1,2,3,4,5,"Hello","job",True,False,None,[1,2,3]]
print(change_list)
change_list[0]="change1"
print(change_list)
change_list[-1]="change_list"
print(change_list)
change_list[0:3]=["Hello"]
print(change_list)
change_list.insert(4,"booby")
print(change_list)
change_list.append("append")
print(change_list)
print("==================================================")
first=[1,2,3,4,5]
second=[6,7,8,9,10]
third=first+second
print(third)
first.extend(second)
print(first)
print(second)